# Build configuration for the FLS language (Bytecode VM version)


# To use it use c-builder --force, or c-builder --help for more indormation, DONT USE c-builder build, AT ALL, dont use the build statement at all
output_name = "fls"

# The source files required for the new, faster bytecode VM.
sources = [
    "src/main.c",
    "src/memory.c",
    "src/chunk.c",
    "src/debug.c",
    "src/value.c",
    "src/object.c",
    "src/table.c",
    "src/lexer.c",
    "src/compiler.c",
    "src/error.c",
    "src/vm.c",
    "std/src/io.c",
    "std/src/math.c",
    "std/src/random.c",
    "std/src/dict.c",
]

include_dirs = [
    "include",
    "std/include",
]

libs = ["m"]

linker_flags = ["-lm", "-pthread"]

# Build modes
build_mode = "release"
optimization_level = "Os"

# Compiler and linker flags
compiler_flags = [
    "-Wall",
    "-Wextra",
    "-pthread",
    "-g",
]

# Add these flags to see the bytecode and VM execution trace for debugging
# debug_flags = ["-DDEBUG_PRINT_CODE", "-DDEBUG_TRACE_EXECUTION"]
